### ISSUE TITLE
mk is not working in ubuntu

### ISSUE THREAD

**Issue by sonulohani** [bill-auger/av-caster#35]
mk is throwing error while running in ubuntu terminal. This is the output of the command:-
sonulohani@ubuntu:~/dev/av-caster/Builds/Scripts$ ./mk
./mk: line 21: cd: Builds/Makefile: No such file or directory
./mk: line 24: cd: /code/dot: No such file or directory

**Comment by bill-auger** [comment]
@sonulohani - the Builds/Scripts/README.md says to first run the script Builds/Scripts/setup-build-helpers - that copies the helper scripts to the project root dir - they are kept in the Scripts dir only so not to clutter the root dir in the repo - that error is because the ./mk script should be run from the project root dir

it is not necessary to use those tho - they mostly exist to help with debugging - the project can be built in the standard *nix way - just cd in to the build dir and make - a new directory will be created beside the Makefile named 'build' - inside is the binary to run named 'av-caster-dbg'

```
cd Builds/Makefile
make && build/av-caster-dbg
```

**Comment by bill-auger** [comment]
also this does not qualify as an "enhancement" - that is something (as opposed to a "feature") that the end-user would notice as an improvement that is not necessarily a new functinoality - for example design or speed improvements

if anything this woud be a "bug" except that it is not
