### ISSUE TITLE
AvCaster for Android

### ISSUE THREAD

**Issue by 06needhamt** [bill-auger/av-caster#53]
see PR https://github.com/bill-auger/av-caster/pull/52 for av-caster configured for android

**Comment by bill-auger** [comment]
added build configuration for android studio
c3f59d8

**Comment by bill-auger** [comment]
@06needhamt -
when you say it is building i assume this means it is creating an executable - but the Gstreamer class is calling into the libgstreamer library and this is not specified in the Projucer - are you actually linking to some version of gstreamer somehow? - what happens when you run the executable? does the GUI launch properly?

**Comment by bill-auger** [comment]
@06needhamt -

i have not heard any news lately about the status of the android port and the commits associated with the PR linked above seem to have been deleted so i have removed the android build configuration from the trunk - if you wish to continue on this port i would be happy to re-introduce it and merge your changes

related PRs --> #51 #52
