### ISSUE TITLE
Porting av-caster UI to Qt

### ISSUE THREAD

**Issue by sonulohani** [bill-auger/av-caster#56]
I can develop a new Qt port of this application. I have seen that some of the users are facing the issue with minimizing the application to the taskbar which can be easily done using Qt framework. Even i have seen some layouting issues while resizing the windows. Please let me know. We can take this further and after your approval i can start working on this feature. Even Qt is well supported for cross platform desktop os as well as for mobile.

**Comment by bill-auger** [comment]
the issue you speak of are really non-issues - av-caster does not minimize to the taskbar only because (along with most everything non-functional) that feature has not been implemented yet but it would not be necessary to switch toolkits to implement this - likewise for the layout - JUCE handles dynamic layout quite well - there is no layout issue resizing the av-caster window because currently the av-caster window is locked at a fixed size but this is only for simplicity as there is no reason to have ti be arbitrarily resizable - ideally it should have a very minimalistic style such as a skinned media player

as you know the current GUI is built with JUCE but JUCE is more than just a GUI framework - it is a complete standard library comparable to QT with data structures, threads, and IO

to port only the views to another toolkit would mean having three complete standard libraries because gStreamer already requires another standard library gLib

to remove JUCE completely would mean modifying nearly every LOC in the entire program - i am not totally against the idea because is would be nice to use include only one standard library but adding QT would not allow for that and i dont think QT would offer any benefit as a replacement for JUCE

ive never used QT directly but what i have heard about it is that it is the heaviest toolkit there is and one of the prime design goals of av-caster is to be as lightweight as possible

as long as av-caster is using gStreamer (which requires gLib) then the obvious choice of a replacement GUI toolkit is one that is based on gLib/gObject such as GTK or clutter - check out clutter it looks quire interesting

if you would like to improve the design please do but i dont see any reason to change toolkit - the choice of toolkit should be quite orthogonal to the actual design - i think if you gave JUCE a chance you may like it - especially with it new live GUI update feature you may find yourself more productive using the projucer than QT designer

* julian give quite a complete [JUCE GUI tutorial here](https://www.youtube.com/watch?v=xsCZoE1s_uw)
* i have created several dedicated [design issues here](https://github.com/bill-auger/av-caster/issues?q=design+is%3Aopen)

**Comment by bill-auger** [comment]
the issue you speak of are really non-issues - av-caster does not minimize to the taskbar only because (along with most everything non-functional) that feature has not been implemented yet but it would not be necessary to switch toolkits to implement this - likewise for the layout - JUCE handles dynamic layout quite well - there is no layout issue resizing the av-caster window because currently the av-caster window is locked at a fixed size but this is only for simplicity as there is no reason to have ti be arbitrarily resizable - ideally it should have a very minimalistic style such as a skinned media player

as you know the current GUI is built with JUCE but JUCE is more than just a GUI framework - it is a complete standard library comparable to QT with data structures, threads, and IO

to port only the views to another toolkit would mean having three complete standard libraries because gStreamer already requires another standard library gLib

to remove JUCE completely would mean modifying nearly every LOC in the entire program - i am not totally against the idea because is would be nice to use include only one standard library but adding QT would not allow for that and i dont think QT would offer any benefit as a replacement for JUCE - in fact i would probably ensure that i would not maintain any ports other than windows7+

ive never used QT directly but what i have heard about it is that it is the heaviest toolkit there is and one of the prime design goals of av-caster is to be as lightweight as possible

as long as av-caster is using gStreamer (which requires gLib) then the obvious choice of a replacement GUI toolkit is one that is based on gLib/gObject such as GTK or clutter - check out clutter it looks quite interesting

if you would like to improve the design please do but i dont see any reason to change toolkit - the choice of toolkit should be quite orthogonal to the actual design - i think if you gave JUCE a chance you may like it - especially with it new live GUI update feature you may find yourself more productive using the projucer than QT designer - here are some links to get you started if you are interested:
- julian give quite a complete [JUCE GUI video tutorial here](https://www.youtube.com/watch?v=xsCZoE1s_uw)
- i have created several dedicated [design issues here](https://github.com/bill-auger/av-caster/issues?q=design+is%3Aopen)

**Comment by sonulohani** [comment]
Ok. I might need to agree on whatever you've discussed here. I would better focus on the design issue. Let me check one of the issue which i am confortable with.
