### ISSUE TITLE
Segmentation Fault (ArchLinux)

### ISSUE THREAD

**Issue by ernestoacostame** [bill-auger/av-caster#62]
Hi. I installed av-caster in ArchLinux using AUR, however when I run it in the terminal (because it does not appear in the applications menu), it throws this error:

``amdy:~ $ av-caster 
gStreamer v1.14.1.0
AvCaster v0.16.003
[GUI]:     chat font size changed from 14 to 16
[GUI]:     hiding chat panel
[1]    10341 segmentation fault (core dumped)  av-caster``

What could be happening?

**Comment by bill-auger** [comment]
some TLC is surely needed - i have not given this program much attention since the end of 2016 - i fixed the segfaults today - i did not try all of the features though - feel free to post bug reports for anything that does not work

it may be some time before the AUR is updated - there is an updated PKGBUILD on the dev branch of this repo https://raw.githubusercontent.com/bill-auger/av-caster/development/Builds/Packaging/PKGBUILD

**Comment by fa7ad** [comment]
@bill-auger sorry for not updating the AUR sooner, I just updated it with your PKGBUILD

**Comment by bill-auger** [comment]
fa7ad -

sooner? i only updated it yesterday - that was amazingly fast - that commit is still on the dev branch - i was not even going to bother you with it yet until i knew is working well

it is a definite improvement though - it was not even starting yesterday

**Comment by l0ophole** [comment]
@bill-auger I just did a "git clone" and built from source with your new PKGBUILD on Archlinux and I'm getting a SEGFAULT.

Running with gdb shows this:
```

Reading symbols from ./av-caster...
(No debugging symbols found in ./av-caster)
(gdb) run
Starting program: /home/rpf/av-caster/Builds/Makefile/build/av-caster 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
gStreamer v1.18.0.0
AvCaster v0.16.003
[Detaching after fork from child process 2261774]
[Detaching after fork from child process 2261775]
[GUI]:     chat font size changed from 14 to 16
[GUI]:     hiding chat panel

Program received signal SIGSEGV, Segmentation fault.
0x0000555555682420 in juce::ValueTree::operator[](juce::Identifier const&) const ()

```
Even with the new PKGBUILD, to get it to compile I had to modify juce_PixelFormats.h and juce_RenderingHelpers.h accoording to [commit 4e0adb2](https://github.com/juce-framework/JUCE/commit/4e0adb2af8b424c43d22bd431011c9a6c57d36b6) in the main juce-framework repo.

Any ideas?

**Comment by bill-auger** [comment]
@l0ophole -

i did not confirm your problem exactly; but i did confirm that av-caster is broken on arch

regarding your specific issue, i notice the log has "AvCaster v0.16.003" - it looks like you built from the master branch - the PKGBUILD in the link above, was for v0.16.005 - i had to compile v0.16.005 with GCC v8; but even then, it would not compile;, because JUCE v4 expects an earlier libc - AvCaster v0.16.003 used an even earlier version of JUCE; so i cant imagine how you got it to compile, or how i could track down a segfault
in AvCaster v0.16.003 on a current arch system

i will re-open this ticket; but this issue would have been better as a new ticket - this ticket was closed two years ago; and it was regarding a different issue - the problem today is not a bug - AvCaster just needs routine maintenance, eg: upgrading JUCE, re-work the packaging

**Comment by bill-auger** [comment]
the development branch is working again on arch now; and i updated the PKGBUILD using a temporary tag 'v0.16.005pre6rc3'

https://raw.githubusercontent.com/bill-auger/av-caster/development/Builds/Packaging/PKGBUILD
